version: '3'
services:
  web:
    build: .
    ports:
      - "80:80"
    networks:
      - webnet
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
