version: "3"

services:
  web:
    build: .
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql
    environment:
      - PMA_ARBITRARY=1
    ports:
      - "8082:80"
    restart: always

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=your_root_password    # Hasło root (możesz je zostawić bez zmian)
      - MYSQL_DATABASE=hobbyhub                    # Zmiana nazwy bazy danych na "hobbyhub"
      - MYSQL_USER=user                            # Zmiana użytkownika na "user"
      - MYSQL_PASSWORD=user123                     # Zmiana hasła na "user123"
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init-scripts:/docker-entrypoint-initdb.d
    restart: always

volumes:
  db_data:
