version: "3"

services:
  web:
    build: .
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql
    environment:
      - PMA_ARBITRARY=1
    ports:
      - "8082:80"
    restart: always

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=your_root_password    # Hasło root
      - MYSQL_DATABASE=hobbyhub                    # Nazwa bazy danych
      - MYSQL_USER=user                            # Użytkownik bazy danych
      - MYSQL_PASSWORD=user123                     # Hasło użytkownika
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init-scripts:/docker-entrypoint-initdb.d  # Pliki do załadowania przy pierwszym uruchomieniu
    restart: always

volumes:
  db_data:
